<?php
/**
 *  $DESCRIPTION$ $END$
 * @name UserController.php
 * @copyright 2024 Riverland Technology Services/OpenPOS
 */

namespace OpenPOS\Controllers;

use OpenPOS\Controllers\BaseController;
use OpenPOS\Controllers\BaseControllerInterface;

class UserController extends BaseController implements BaseControllerInterface
{
    public function get(array $args): void
    {
        parent::get($args); // TODO: Change the autogenerated stub
    }

    public function post(array $args): void
    {
        parent::post($args);
    }

    public function put(array $args): void
    {
        parent::put($args);
    }

    public function delete(array $args): void
    {
        parent::delete($args);
    }
}